#!/bin/bash

if [ $# == "1" ]; then
  if ! [ -e $1 ]; then
    echo "Source scheme file not found '$1'"
    exit
  fi
  DEBUG=""
  FILE=$1
elif [ $# == "2" ]; then
  if ! [ $1 == "--debug" ]; then
      echo "--debug expected"
      exit
  fi
  if ! [ -e $2 ]; then
    echo "Source scheme file not found '$2'"
    exit
  fi
  DEBUG="--debug"
  FILE=$2
else
  echo "Usage: cschemea <filename>"
  exit
fi

./csc-comp --mode=analysis $DEBUG $FILE
